export const SIDEBAR_OPEN = "SIDEBAR_OPEN";
export const SIDEBAR_CLOSE = "SIDEBAR_CLOSE";
export const GET_PRODUCTS_BEGIN = "GET_PRODUCTS_BEGIN";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR";
export const GET_SINGLE_PRODUCT_BEGIN = "GET_SINGLE_PRODUCT_BEGIN";
export const GET_SINGLE_PRODUCT_SUCCESS = "GET_SINGLE_PRODUCT_SUCCESS";
export const GET_SINGLE_PRODUCT_ERROR = "GET_SINGLE_PRODUCT_ERROR";
export const LOAD_PRODUCTS = "LOAD_PRODUCTS";
export const SET_GRIDVIEW = "SET_GRIDVIEW";
export const SET_LISTVIEW = "SET_LISTVIEW";
export const UPDATE_SORT = "UPDATE_SORT";
export const SORT_PRODUCTS = "SORT_PRODUCTS";
export const UPDATE_FILTERS = "UPDATE_FILTERS";
export const FILTER_PRODUCTS = "FILTER_PRODUCTS";
export const CLEAR_FILTERS = "CLEAR_FILTERS";

export const GET_CART_BEGIN = "GET_CART_BEGIN";
export const GET_CART_ERROR = "GET_CART_ERROR";
export const GET_CART_SUCCESS = "GET_CART_SUCCESS";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const TOGGLE_CART_ITEM_AMOUNT = "TOGGLE_CART_ITEM_AMOUNT";
export const CLEAR_CART = "CLEAR_CART";
export const COUNT_CART_TOTALS = "COUNT_CART_TOTALS";

export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS";
export const GET_ORDER_FAIL = "GET_ORDER_FAIL";
export const TRANSFER_ORDER_SUCCESS = "TRANSFER_ORDER_SUCCESS";
export const TRANSFER_ORDER_FAIL = "TRANSFER_ORDER_FAIL";

export const GET_CATEGORIES_BEGIN = "GET_CATEGORIES_BEGIN";
export const GET_CATEGORIES_ERROR = "GET_CATEGORIES_ERROR";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_SINGLE_CATEGORY_BEGIN = "GET_SINGLE_CATEGORY_BEGIN";
export const GET_SINGLE_CATEGORY_ERROR = "GET_SINGLE_CATEGORY_ERROR";

export const GET_COLORS_BEGIN = "GET_COLORS_BEGIN";
export const GET_COLORS_ERROR = "GET_COLORS_ERROR";
export const GET_COLORS_SUCCESS = "GET_COLORS_SUCCESS";

export const FILTER_PRODUCTS_CATEGORY = "FILTER_PRODUCTS_CATEGORY";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_INFO_REQUEST = "USER_INFO_REQUEST";
export const USER_INFO_SUCCESS = "USER_INFO_SUCCESS";
export const USER_INFO_FAIL = "USER_INFO_FAIL";

export const USER_INFO_UPDATE_REQUEST = "USER_INFO_UPDATE_REQUEST";
export const USER_INFO_UPDATE_SUCCESS = "USER_INFO_UPDATE_SUCCESS";
export const USER_INFO_UPDATE_FAIL = "USER_INFO_UPDATE_FAIL";
export const USER_CHANGE_PASSWORD_SUCCESS = "USER_CHANGE_PASSWORD_SUCCESS";
export const USER_CHANGE_PASSWORD_FAIL = "USER_CHANGE_PASSWORD_FAIL";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const COMMENT_REQUEST = "COMMENT_REQUEST";
export const COMMENT_REQUEST_SUCCESS = "COMMENT_REQUEST_SUCCESS";
export const COMMENT_REQUEST_FAIL = "COMMENT_REQUEST_FAIL";
